# Generated by Django 5.1.6 on 2026-07-14 07:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BellPartial',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Aangemaakt op')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Bijgewerkt op')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('partial', models.CharField(choices=[('hum', 'Zoemtoon (Hum)'), ('prime', 'Grondtoon (Prime)'), ('tierce', 'Terts (Tierce)'), ('quint', 'Kwint (Quint)'), ('nominal', 'Nominaal (Nominal)'), ('superquint', 'Superkwint (Superquint)'), ('octave_nominal', 'Octaafnominaal'), ('andere', 'Andere')], max_length=20, verbose_name='Boventoon')),
                ('frequency', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Frequentie (Hz)')),
                ('note', models.CharField(blank=True, max_length=20, null=True, verbose_name='Noot')),
                ('cents_deviation', models.FloatField(blank=True, null=True, verbose_name='Afwijking (cents)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Opmerkingen')),
            ],
            options={
                'verbose_name': 'Boventoon',
                'verbose_name_plural': 'Boventonen',
                'ordering': ['bell', 'frequency'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Aangemaakt op')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Bijgewerkt op')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Onderwerp')),
                ('message', models.TextField(verbose_name='Bericht')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Opgelost')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='bell_founder',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bell_tower',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='carillon_bell',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bell',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Aangemaakt op'),
        ),
        migrations.AddField(
            model_name='bell',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door'),
        ),
        migrations.AddField(
            model_name='bell',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Vrije, zelf gedefinieerde eigenschappen als sleutel/waarde-paren', verbose_name='Extra velden'),
        ),
        migrations.AddField(
            model_name='bell',
            name='ornaments',
            field=models.TextField(blank=True, null=True, verbose_name='Versieringen'),
        ),
        migrations.AddField(
            model_name='bell',
            name='profile',
            field=models.CharField(blank=True, help_text='Bijvoorbeeld: zwaar, licht of medium profiel', max_length=100, null=True, verbose_name='Profiel'),
        ),
        migrations.AddField(
            model_name='bell',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Bijgewerkt op'),
        ),
        migrations.AddField(
            model_name='bell_founder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Aangemaakt op'),
        ),
        migrations.AddField(
            model_name='bell_founder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door'),
        ),
        migrations.AddField(
            model_name='bell_founder',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Bijgewerkt op'),
        ),
        migrations.AddField(
            model_name='bell_tower',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Aangemaakt op'),
        ),
        migrations.AddField(
            model_name='bell_tower',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door'),
        ),
        migrations.AddField(
            model_name='bell_tower',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Bijgewerkt op'),
        ),
        migrations.AddField(
            model_name='carillon',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Aangemaakt op'),
        ),
        migrations.AddField(
            model_name='carillon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door'),
        ),
        migrations.AddField(
            model_name='carillon',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Vrije, zelf gedefinieerde eigenschappen als sleutel/waarde-paren', verbose_name='Extra velden'),
        ),
        migrations.AddField(
            model_name='carillon',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Bijgewerkt op'),
        ),
        migrations.AddField(
            model_name='carillon_bell',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Aangemaakt op'),
        ),
        migrations.AddField(
            model_name='carillon_bell',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door'),
        ),
        migrations.AddField(
            model_name='carillon_bell',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Bijgewerkt op'),
        ),
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Aangemaakt op'),
        ),
        migrations.AddField(
            model_name='file',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door'),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Bijgewerkt op'),
        ),
        migrations.AddField(
            model_name='founder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Aangemaakt op'),
        ),
        migrations.AddField(
            model_name='founder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door'),
        ),
        migrations.AddField(
            model_name='founder',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Vrije, zelf gedefinieerde eigenschappen als sleutel/waarde-paren', verbose_name='Extra velden'),
        ),
        migrations.AddField(
            model_name='founder',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Bijgewerkt op'),
        ),
        migrations.AddField(
            model_name='tower',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Aangemaakt op'),
        ),
        migrations.AddField(
            model_name='tower',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door'),
        ),
        migrations.AddField(
            model_name='tower',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Vrije, zelf gedefinieerde eigenschappen als sleutel/waarde-paren', verbose_name='Extra velden'),
        ),
        migrations.AddField(
            model_name='tower',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Bijgewerkt op'),
        ),
        migrations.AlterField(
            model_name='bell',
            name='function',
            field=models.CharField(blank=True, choices=[('luidklok', 'Luidklok'), ('uurklok', 'Uurklok'), ('beiaardklok', 'Beiaardklok'), ('gelui', 'Gelui'), ('andere', 'Andere')], max_length=100, null=True, verbose_name='Functie'),
        ),
        migrations.AlterField(
            model_name='bell_founder',
            name='bell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founder_links', to='inventory.bell'),
        ),
        migrations.AlterField(
            model_name='bell_founder',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bell_links', to='inventory.founder'),
        ),
        migrations.AlterField(
            model_name='bell_tower',
            name='bell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_links', to='inventory.bell'),
        ),
        migrations.AlterField(
            model_name='bell_tower',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bell_links', to='inventory.tower'),
        ),
        migrations.AlterField(
            model_name='carillon',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carillons', to='inventory.tower', verbose_name='Toren'),
        ),
        migrations.AlterField(
            model_name='carillon_bell',
            name='bell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carillon_links', to='inventory.bell'),
        ),
        migrations.AlterField(
            model_name='carillon_bell',
            name='carillon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bell_links', to='inventory.carillon'),
        ),
        migrations.AlterField(
            model_name='file',
            name='bell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inventory.bell', verbose_name='Klok'),
        ),
        migrations.AlterField(
            model_name='file',
            name='carillon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inventory.carillon', verbose_name='Beiaard'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=inventory.models.file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp', 'pdf', 'csv'])], verbose_name='Bestand'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'Image (png, jpg, jpeg, svg, webp)'), ('pdf', 'PDF'), ('csv', 'CSV')], help_text='Automatisch afgeleid uit het bestand indien leeg gelaten', max_length=10, verbose_name='Bestandstype'),
        ),
        migrations.AlterField(
            model_name='file',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inventory.founder', verbose_name='Gieter'),
        ),
        migrations.AlterField(
            model_name='file',
            name='tower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inventory.tower', verbose_name='Toren'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='alternative_names',
            field=models.JSONField(blank=True, default=list, help_text='Lijst van alternatieve namen', verbose_name='Alternatieve namen'),
        ),
        migrations.AddIndex(
            model_name='bell',
            index=models.Index(fields=['name'], name='inventory_b_name_9c9934_idx'),
        ),
        migrations.AddIndex(
            model_name='bell',
            index=models.Index(fields=['year'], name='inventory_b_year_45da54_idx'),
        ),
        migrations.AddIndex(
            model_name='bell',
            index=models.Index(fields=['pitch'], name='inventory_b_pitch_8bd8db_idx'),
        ),
        migrations.AddIndex(
            model_name='bell',
            index=models.Index(fields=['weight'], name='inventory_b_weight_59ea2a_idx'),
        ),
        migrations.AddIndex(
            model_name='bell',
            index=models.Index(fields=['function'], name='inventory_b_functio_cb457f_idx'),
        ),
        migrations.AddIndex(
            model_name='carillon',
            index=models.Index(fields=['established'], name='inventory_c_establi_ff48ab_idx'),
        ),
        migrations.AddIndex(
            model_name='founder',
            index=models.Index(fields=['primary_name'], name='inventory_f_primary_8be372_idx'),
        ),
        migrations.AddIndex(
            model_name='founder',
            index=models.Index(fields=['country'], name='inventory_f_country_615375_idx'),
        ),
        migrations.AddIndex(
            model_name='tower',
            index=models.Index(fields=['name'], name='inventory_t_name_c37726_idx'),
        ),
        migrations.AddIndex(
            model_name='tower',
            index=models.Index(fields=['city'], name='inventory_t_city_87a96a_idx'),
        ),
        migrations.AddConstraint(
            model_name='bell_founder',
            constraint=models.UniqueConstraint(fields=('bell', 'founder', 'type_of_work', 'date_of_work'), name='uniq_bell_founder_work'),
        ),
        migrations.AddConstraint(
            model_name='bell_tower',
            constraint=models.UniqueConstraint(fields=('tower', 'bell', 'start_date'), name='uniq_bell_tower_period'),
        ),
        migrations.AddConstraint(
            model_name='carillon_bell',
            constraint=models.UniqueConstraint(fields=('carillon', 'bell', 'start_date'), name='uniq_carillon_bell_period'),
        ),
        migrations.AddField(
            model_name='bellpartial',
            name='bell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partials', to='inventory.bell', verbose_name='Klok'),
        ),
        migrations.AddField(
            model_name='bellpartial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['content_type', 'object_id'], name='inventory_f_content_ed2f93_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['is_resolved'], name='inventory_f_is_reso_dbf892_idx'),
        ),
    ]
