# Generated by Django 5.1.6 on 2026-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bellpartial_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contact',
            field=models.CharField(blank=True, help_text='Optioneel — zodat we kunnen terugkoppelen.', max_length=200, null=True, verbose_name='Naam of e-mail'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='page_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Pagina'),
        ),
    ]
